on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]

name: Build and Verify

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.100'

      - name: Install report coverage utility
        run: dotnet tool install --global dotnet-reportgenerator-globaltool
      - name: Build solution
        run: dotnet build
      - name: Run tests with coverage
        run: dotnet test --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura
     
      - name: Aggregate coverage
        run: reportgenerator -reports:**/coverage.cobertura.xml -targetdir:CoberturaReports -reporttypes:"Lcov"

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./CoberturaReports/lcov.info         